# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c69bae15ccf3305feb41c634c88d5d88e516986c08162ffb3a99ecc76915b05ae8d23ba298f2d49a3c7934e8ac0d0a63d2db1269aa0388ae8eae973ca9a3e98b

test:
  secret_key_base: 25bc9cb0e4271acae26f85cf2a9608ef99b6f93c71f9cdca9476ea9808d4c0e8964b2c8ff9b77ef8249db0dba43287b5427b710fcbad034e34f61886aad66b46

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
